// Each new term in the Fibonacci sequence is generated by
// adding the previous two terms. By starting with 1 and 2,
// the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values
// do not exceed four million, find the sum of the even-valued terms.

package main

import "fmt"

func main() {
	fmt.Printf("Sum of even fib terms is %d\n", evenFibSum(35))
	fmt.Printf("Sum of even fib terms is %d\n", evenFibSum(4000000))
}

func evenFibSum(maxVal int) int {
	sum := 0
	second := 1
	first := 2
	for first <= maxVal {
		newfirst := first + second
		second = first
		if second%2 == 0 {
			sum += second
		}
		first = newfirst
	}
	return sum
}
